title: Marta Tornero
description: Escritora, investigadora y comunicadora sobre colapso, comunidad y cuidado. 
url: "https://martatornero.com"  # sin / al final
baseurl: "" # déjalo vacío si está en el root del dominio
lang: es

locale: es_ES
timezone: Europe/Madrid # Necesita la gem 'tzinfo-data'

favicon: 'assets/favicon.ico'

author:
  name: "Marta Tornero"
  email: "permaprendices@gmail.com"
  url: "https://martatornero.com"
email: "permaprendices@gmail.com"

social:
  name: Marta Tornero
  links:
    - https://instagram.com/martatornero
    - https://permaprendices.substack.com

twitter:
  username: martatornero

feed:
  path: feed.xml
  excerpt_only: true

defaults:
  - scope:
      path: ""
    values:
      lang: "es"
  - scope:
      path: "es" # Si está en la carpeta es/
    values:
      lang: "es" # Suponemos que el lang es "es"
  - scope:
      path: "en" # Si está en la carpeta en/
    values:
      lang: "en" # Suponemos que el lang es "en"

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-feed
